filebeat.inputs:
  - type: log
    id: ot-log-generator
    enabled: true
    paths:
      - /var/log/ot-traffic.log
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      generator_host: vm3-generator

  - type: log
    id: auditbeat-sockets
    enabled: true
    paths:
      - /var/log/auditbeat/auditbeat*
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      beat_type: auditbeat

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

output.logstash:
  hosts: ["10.128.0.16:5044"]
  ssl.enabled: false
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

setup.kibana:
